# Generated by Django 4.2.1 on 2023-07-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_customer_order_delete_computer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
