# Generated by Django 4.2.1 on 2023-07-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_computerdetail_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='computerdetail',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
