# Generated by Django 4.2.1 on 2023-07-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_remove_computerdetail_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='compplete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
