# Generated by Django 4.2.1 on 2023-07-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_order_compplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='compplete',
            new_name='complete',
        ),
    ]
